87kangsw/GitTime

GitTime/Sources/Models/TrendDeveloper.swift, GitTime/Sources/Models/TrendRepo.swift, GitTime/Sources/Network/GitTimeCralwerAPI.swift, GitTime/Sources/Services/GitTimeCrawlerService.swift, GitTime/Sources/Utils/Extensions/String+Extensions.swift, GitTime/Sources/ViewControllers/Trend/TrendViewReactor.swift
- 기존 API 사용을 안하고 직접 깃허브 사이트에서 필요 데이터를 파싱하는 로직을 추가하였습니다. 
- `Trending Repository` , `Trending Developers` 두가지 기능 모두 추가 되었습니다.
=> [Feature] Github Parser 추가

Podfile, Podfile.lock
=> # Pod update

GitTime/Sources/Utils/Enum/ContributionHexColorTypes.swift, GitTime/Sources/ViewControllers/Activity/ActivityViewReactor.swift
- `fill` 키값 제거 이후 `data-date` 값이 새로 생겨 대응하였습니다.
=> Github Contributions 로직 변경 대응

.github/workflows/ci.yml
- update Xcode Version, Simulator
=> fix GitHubAction Failed 

CHANGELOG.md, Gemfile.lock, Makefile, fastlane/Fastfile, fastlane/Matchfile, fastlane/Pluginfile, fastlane/README.md
- add Firebase distribution upload
=> Fastlane Update

GitTime/Sources/Utils/Extensions/Date+Extensions.swift, GitTime/Sources/ViewControllers/Activity/ActivityViewReactor.swift, GitTime/Sources/ViewControllers/Buddy/BuddyViewController.swift, GitTime/Sources/ViewControllers/Buddy/BuddyViewReactor.swift, fastlane/Fastfile, fastlane/README.md
=> 버디 메뉴 기능 추가

GitTime.xcodeproj/project.pbxproj, GitTime/Sources/ViewControllers/Trend/TrendViewReactor.swift
- Trending Repo / Developer 파싱 에러 수정
=> [Release] v1.3.4

GitTime.xcodeproj/project.pbxproj, GitTime/Sources/Views/Activity/ActivityContributionView.swift
=> Master to Develop 

GitTime/Sources/GlobalStates.swift, GitTime/Sources/Models/Trial/contributions_dark.json, GitTime/Sources/Models/Trial/contributions_light.json, GitTime/Sources/ViewControllers/Activity/ActivityViewReactor.swift, GitTime/Sources/ViewControllers/Login/LoginViewReactor.swift, GitTime/Sources/ViewControllers/Setting/SettingViewReactor.swift
=> Trial Mode

CHANGELOG.md, GitTime/Sources/ViewControllers/Trend/TrendViewReactor.swift, GitTime/Supporting Files/Info.plist
- 핫픽스 2.0.2 릴리즈
- Trending Developer 아바타 parsing error 수정
=> [Release] 2.0.2

CHANGELOG.md, GitTime/Sources/Utils/Extensions/String+Extensions.swift, GitTime/Sources/ViewControllers/Buddy/BuddyViewReactor.swift, GitTime/Sources/Views/Buddy/BuddyDailyCell.swift, GitTime/Supporting Files/Info.plist
- 2.0.3 릴리즈 merge
- GitHub의 사용자명 포맷 변경으로 인해 이름에 `\n`이 포함된 상태로 Realm에 등록되는.. Buddy Tab 오류 수정
=> [Release] 2.0.3

GitTime/Sources/Utils/Constants/BundleInfoConfig.swift, GitTime/Sources/Utils/Constants/Constants.swift, GitTime/Sources/Utils/Constants/UserDefaultsConfig.swift, GitTime/Sources/ViewControllers/Setting/SettingViewController.swift, GitTime/Sources/ViewControllers/Setting/SettingViewReactor.swift
- 앱스토어 평가 유도 팝업 추가
- SKStoreReviewController 추가
- [애플문서](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/requesting_app_store_reviews) 참고하여 추가..
=> 앱스토어 평가 유도 팝업 추가

CHANGELOG.md, GitTime/Sources/CompositionRoot.swift, GitTime/Sources/Utils/Constants/BundleInfoConfig.swift, GitTime/Sources/Utils/Constants/Constants.swift, GitTime/Sources/Utils/Constants/UserDefaultsConfig.swift, GitTime/Sources/ViewControllers/Buddy/BuddyViewController.swift, GitTime/Sources/ViewControllers/Setting/SettingViewController.swift, GitTime/Sources/ViewControllers/Setting/SettingViewReactor.swift, GitTime/Supporting Files/Info.plist
- 2.0.4 릴리즈
- 앱리뷰 추천 로직 추가
- 아이패드에서 앱 아이콘 변경되지 않는 문제 수정
- 버디 항목 클릭시, 해당 유저 페이지로 이동
=> [Release] 2.0.4

GitTime/Sources/Utils/Analytics/GitTimeAnalytics.swift, Podfile.lock
- Xcode 12.5 버전 업데이트로 인한 `pod update`
- Identifiable 사용 중인 RealmSwift로 인한 빌드에러
=> 코코아팟 버전 업데이트

BuildScripts/FirebaseCrashlytics.sh, BuildScripts/SwiftLint.sh, GitTime/Supporting Files/Info.plist, project.yml
- FirebaseCrashlytics, SwiftLint build script 추가
- build script 추가
- XcodeGen project.yml 수정
=> FirebaseCrashlytics 추가

GitTime/Sources/ViewControllers/Trend/TrendViewReactor.swift
- 트렌딩 repository parsing 에러 수정
- `f6 color-text-secondary mt-2` 처리된 부분 변경
=> 트렌딩 레포 parsing 수정

GitTime/Sources/Models/FavoriteLanguage.swift, GitTime/Sources/ViewControllers/Activity/ActivityViewReactor.swift, GitTime/Sources/ViewControllers/Buddy/BuddyViewReactor.swift, GitTime/Supporting Files/Info.plist, Makefile, fastlane/Fastfile, fastlane/README.md
- 프로필 이미지 오류
- 즐겨찾는 언어 지정시, 크래시 수정
- 프로필 이미지 오류
- 즐겨찾는 언어 지정시, 크래시 수정
=> [Release] 2.1.2

GitTime/Sources/ViewControllers/Activity/ActivityViewController.swift, GitTime/Sources/Views/Activity/ActivityContributionView.swift
- Activity 탭 UI 이슈 수정
- 프로필 이미지 frame 고정
- collectionView contentOffset 지정되지 않는 오류 수정
=> Activity 오류 수정

GitTime/Sources/Services/RealmService.swift
- 버디 탭 버그 수정
- realm 스키마 버전 bump
=> 버디 탭 버그 수정 

GitTime/Sources/Utils/Extensions/UIImage+Extensions.swift, GitTime/Sources/ViewControllers/Activity/ActivityViewController.swift, GitTime/Sources/ViewControllers/Activity/ActivityViewReactor.swift
- 프로필 이미지 navigation button size 오류 수정
- 이미지 다운로더를 통해 이미지를 다운 후, resize 해서 처리하도록 수정
=> 프로필 이미지 오류 수정

GitTime/Sources/CompositionRoot.swift
=> 이미지 캐시 초기화 적용

GitTime/Sources/Utils/Extensions/Rx/UICollectionView+Rx.swift, GitTime/Sources/ViewControllers/Activity/ActivityViewReactor.swift, GitTime/Sources/Views/Activity/ActivityContributionView.swift
- Contribution 파싱 오류 수정
- 변경된 GitHub html 구조로 변경
- 날짜순으로 데이터 정렬
=> contribution parsing error fix

GitTime/Sources/CompositionRoot.swift, GitTime/Sources/Models/Me.swift, GitTime/Sources/ViewControllers/Activity/ActivityViewReactor.swift, project.yml
- Contribution 파싱하는 처리 대신 GraphQL API를 사용하도록 개선합니다.
- GitHubKit 연동
=> GitHubKit 연동

GitTime/Sources/Views/Activity/ActivityItemCell.swift
- Activitycell 프로필 이미지 expiration 옵션 변경
- 1 day로 변경
=> activitycell 프로필 이미지 expiration 옵션 변경

GitTime/Sources/Models/Event.swift, GitTime/Sources/Models/Payload.swift
- Dateformatter 를 ISO8601DateFormatter로 변경
=> Dateformatter를 iso8601 로 변경

GitTime/Sources/Models/Me.swift, GitTime/Sources/Services/ActivityService.swift, GitTime/Sources/Utils/GitTimeDecodingError.swift, GitTime/Sources/ViewControllers/Login/LoginViewReactor.swift, GitTime/Supporting Files/Info.plist, project.yml
- comment payload에서 발생한 decoding error 수정 ("name")
=> [Hotfix] 2.2.3

BuildScripts/FirebaseCrashlytics.sh, GitTime/Sources/CompositionRoot.swift, project.yml
- Realm 설정이 잘못되어 새로 fork 한 프로젝트에서 빌드되지 않는 문제 수정
- Firebase 설정을 Release 스킴에서만 동작하게 하여 시뮬레이터에서는 동작되도록 변경
=> 빌드 오류 수정 - Realm 설정 오류 / firebase 설정 변경

BuildScripts/FirebaseCrashlytics.sh, GitTime/Sources/CompositionRoot.swift, GitTime/Sources/Models/Trial/contributions_dark.json, GitTime/Sources/Models/Trial/contributions_light.json, GitTime/Sources/Network/GitTimeProvider.swift, GitTime/Sources/Services/AuthService.swift, GitTime/Sources/Utils/Extensions/Date+Extensions.swift, GitTime/Sources/Utils/Extensions/Rx/UIAlertController+Rx.swift, GitTime/Sources/Utils/Extensions/UIColor+Extensions.swift, GitTime/Sources/ViewControllers/Activity/ActivityViewReactor.swift, GitTime/Sources/ViewControllers/Buddy/BuddyViewController.swift, GitTime/Sources/ViewControllers/Buddy/BuddyViewReactor.swift, GitTime/Sources/ViewControllers/Setting/SettingViewController.swift, GitTime/Sources/Views/Activity/ActivityContributionView.swift, GitTime/Supporting Files/Info.plist, GitTime/Supporting Files/PrivacyInfo.xcprivacy, project.yml
- 버디탭 
- Daily 데이터만 처리하도록 변경
- GraphQL로 변경
- 아이패드 오류 수정
- 잔디 UI 이슈 수정
- 로그아웃 되지 않는 오류 수정 
- Privacy Manifest 대응
=> [Release] 2.2.4
